platform :ios, '8.0'
use_frameworks!

target 'RxAlamofireExample' do
  pod 'RxAlamofire/RxCocoa'
  pod 'ObjectMapper'

  pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]
end
